//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMSA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIMSA.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an alphabet.
        /// </summary>
        public static string AddAlphabet {
            get {
                return ResourceManager.GetString("AddAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabet name.
        /// </summary>
        public static string AlphabetName {
            get {
                return ResourceManager.GetString("AlphabetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabets.
        /// </summary>
        public static string Alphabets {
            get {
                return ResourceManager.GetString("Alphabets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braille alphabet.
        /// </summary>
        public static string BraillePageTitle {
            get {
                return ResourceManager.GetString("BraillePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit alphabet.
        /// </summary>
        public static string EditAlphabetPageTitle {
            get {
                return ResourceManager.GetString("EditAlphabetPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English alphabet.
        /// </summary>
        public static string EnglishAlphabet {
            get {
                return ResourceManager.GetString("EnglishAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        public static string Invert {
            get {
                return ResourceManager.GetString("Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letters of the alphabet.
        /// </summary>
        public static string LettersOfTheAlphabet {
            get {
                return ResourceManager.GetString("LettersOfTheAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICE.
        /// </summary>
        public static string MenuPageTitle {
            get {
                return ResourceManager.GetString("MenuPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morse code.
        /// </summary>
        public static string MorsePageTitle {
            get {
                return ResourceManager.GetString("MorsePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New alphabet.
        /// </summary>
        public static string NewAlphabet {
            get {
                return ResourceManager.GetString("NewAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number code.
        /// </summary>
        public static string NumericPageTitle {
            get {
                return ResourceManager.GetString("NumericPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric value of the first letter.
        /// </summary>
        public static string NumericValueOfTheFirstLetter {
            get {
                return ResourceManager.GetString("NumericValueOfTheFirstLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radix.
        /// </summary>
        public static string Radix {
            get {
                return ResourceManager.GetString("Radix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select alphabet.
        /// </summary>
        public static string SelectAlphabetPageTitle {
            get {
                return ResourceManager.GetString("SelectAlphabetPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator.
        /// </summary>
        public static string Separator {
            get {
                return ResourceManager.GetString("Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode.
        /// </summary>
        public static string Unicode {
            get {
                return ResourceManager.GetString("Unicode", resourceCulture);
            }
        }
    }
}
